# Generated by Django 4.2.2 on 2023-06-19 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_categoriesimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesimg',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.categories'),
            preserve_default=False,
        ),
    ]
