# Generated by Django 4.2.2 on 2023-06-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_categoriesimg_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriesimg',
            old_name='categories',
            new_name='categories_img',
        ),
    ]
