# Generated by Django 4.2.2 on 2023-06-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_categories_img_categoriesimg_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriesImg',
        ),
    ]
