# Generated by Django 4.2.2 on 2023-06-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_employeedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
