# Generated by Django 4.2.2 on 2023-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_alter_ideamodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideamodel',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
